services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: jima:0.1.0
    container_name: jima
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      JIMA_POSTGRES_DB_HOST: db
      JIMA_POSTGRES_DB_PORT: ${JIMA_POSTGRES_DB_PORT}
      JIMA_POSTGRES_DB_NAME: ${JIMA_POSTGRES_DB_NAME}
      JIMA_POSTGRES_DB_USER: ${JIMA_POSTGRES_DB_USER}
      JIMA_POSTGRES_DB_PASSWORD: ${JIMA_POSTGRES_DB_PASSWORD}
      JIMA_POSTGRES_DB_SSL_MODE: disable
      JIMA_ENVIRONMENT: production
      JIMA_PORT: 8080
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    container_name: jima-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/jima
      - ./script/initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
